{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "centaur.componentName" (dict "root" . "component" "postgres") }}
  labels:
{{ include "centaur.componentLabels" (dict "root" . "component" "postgres") | nindent 4 }}
spec:
  selector:
{{ include "centaur.componentSelectorLabels" (dict "root" . "component" "postgres") | nindent 4 }}
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
---
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "centaur.componentName" (dict "root" . "component" "secrets") }}
  labels:
{{ include "centaur.componentLabels" (dict "root" . "component" "secrets") | nindent 4 }}
spec:
  selector:
{{ include "centaur.componentSelectorLabels" (dict "root" . "component" "secrets") | nindent 4 }}
  ports:
    - name: http
      port: 8100
      targetPort: 8100
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "centaur.componentName" (dict "root" . "component" "firewall") }}
  labels:
{{ include "centaur.componentLabels" (dict "root" . "component" "firewall") | nindent 4 }}
spec:
  selector:
{{ include "centaur.componentSelectorLabels" (dict "root" . "component" "firewall") | nindent 4 }}
  ports:
    - name: proxy
      port: {{ .Values.firewall.service.proxyPort }}
      targetPort: {{ .Values.firewall.service.proxyPort }}
    - name: control
      port: {{ .Values.firewall.service.controlPort }}
      targetPort: {{ .Values.firewall.service.controlPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "centaur.componentName" (dict "root" . "component" "pgbouncer") }}
  labels:
{{ include "centaur.componentLabels" (dict "root" . "component" "pgbouncer") | nindent 4 }}
spec:
  selector:
{{ include "centaur.componentSelectorLabels" (dict "root" . "component" "pgbouncer") | nindent 4 }}
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "centaur.componentName" (dict "root" . "component" "api") }}
  labels:
{{ include "centaur.componentLabels" (dict "root" . "component" "api") | nindent 4 }}
spec:
  selector:
{{ include "centaur.componentSelectorLabels" (dict "root" . "component" "api") | nindent 4 }}
  ports:
    - name: http
      port: 8000
      targetPort: 8000
---
{{- if .Values.slackbot.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "centaur.componentName" (dict "root" . "component" "slackbot") }}
  labels:
{{ include "centaur.componentLabels" (dict "root" . "component" "slackbot") | nindent 4 }}
spec:
  selector:
{{ include "centaur.componentSelectorLabels" (dict "root" . "component" "slackbot") | nindent 4 }}
  ports:
    - name: http
      port: 3001
      targetPort: 3001
---
{{- end }}
{{- if .Values.runnerAccess.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "centaur.componentName" (dict "root" . "component" "api-runner") }}
  labels:
{{ include "centaur.componentLabels" (dict "root" . "component" "api") | nindent 4 }}
spec:
  type: {{ .Values.runnerAccess.apiService.type }}
  {{- with .Values.runnerAccess.apiService.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml . | nindent 4 }}
  {{- end }}
  selector:
{{ include "centaur.componentSelectorLabels" (dict "root" . "component" "api") | nindent 4 }}
  ports:
    - name: http
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "centaur.componentName" (dict "root" . "component" "firewall-runner") }}
  labels:
{{ include "centaur.componentLabels" (dict "root" . "component" "firewall") | nindent 4 }}
spec:
  type: {{ .Values.runnerAccess.firewallService.type }}
  {{- with .Values.runnerAccess.firewallService.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml . | nindent 4 }}
  {{- end }}
  selector:
{{ include "centaur.componentSelectorLabels" (dict "root" . "component" "firewall") | nindent 4 }}
  ports:
    - name: proxy
      port: {{ .Values.firewall.service.proxyPort }}
      targetPort: {{ .Values.firewall.service.proxyPort }}
{{- end }}
